/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutenticatedRouteRouteImport } from './routes/_autenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AutenticatedAdvisorRouteImport } from './routes/_autenticated/advisor'
import { Route as AutenticatedCareerTipsRouteImport } from './routes/_autenticated/career-tips'
import { Route as AutenticatedCvAndLettersRouteImport } from './routes/_autenticated/cv-and-letters'
import { Route as AutenticatedGoalSetterRouteImport } from './routes/_autenticated/goal-setter'
import { Route as AutenticatedHomeRouteImport } from './routes/_autenticated/home'
import { Route as ApiAiRouteImport } from './routes/api/ai'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutenticatedRouteRoute = AutenticatedRouteRouteImport.update({
  id: '/_autenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AutenticatedAdvisorRoute = AutenticatedAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AutenticatedRouteRoute,
} as any)
const AutenticatedCareerTipsRoute = AutenticatedCareerTipsRouteImport.update({
  id: '/career-tips',
  path: '/career-tips',
  getParentRoute: () => AutenticatedRouteRoute,
} as any)
const AutenticatedCvAndLettersRoute =
  AutenticatedCvAndLettersRouteImport.update({
    id: '/cv-and-letters',
    path: '/cv-and-letters',
    getParentRoute: () => AutenticatedRouteRoute,
  } as any)
const AutenticatedGoalSetterRoute = AutenticatedGoalSetterRouteImport.update({
  id: '/goal-setter',
  path: '/goal-setter',
  getParentRoute: () => AutenticatedRouteRoute,
} as any)
const AutenticatedHomeRoute = AutenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AutenticatedRouteRoute,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/advisor': typeof AutenticatedAdvisorRoute
  '/career-tips': typeof AutenticatedCareerTipsRoute
  '/cv-and-letters': typeof AutenticatedCvAndLettersRoute
  '/goal-setter': typeof AutenticatedGoalSetterRoute
  '/home': typeof AutenticatedHomeRoute
  '/api/ai': typeof ApiAiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/advisor': typeof AutenticatedAdvisorRoute
  '/career-tips': typeof AutenticatedCareerTipsRoute
  '/cv-and-letters': typeof AutenticatedCvAndLettersRoute
  '/goal-setter': typeof AutenticatedGoalSetterRoute
  '/home': typeof AutenticatedHomeRoute
  '/api/ai': typeof ApiAiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_autenticated': typeof AutenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_autenticated/advisor': typeof AutenticatedAdvisorRoute
  '/_autenticated/career-tips': typeof AutenticatedCareerTipsRoute
  '/_autenticated/cv-and-letters': typeof AutenticatedCvAndLettersRoute
  '/_autenticated/goal-setter': typeof AutenticatedGoalSetterRoute
  '/_autenticated/home': typeof AutenticatedHomeRoute
  '/api/ai': typeof ApiAiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/advisor'
    | '/career-tips'
    | '/cv-and-letters'
    | '/goal-setter'
    | '/home'
    | '/api/ai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/advisor'
    | '/career-tips'
    | '/cv-and-letters'
    | '/goal-setter'
    | '/home'
    | '/api/ai'
  id:
    | '__root__'
    | '/'
    | '/_autenticated'
    | '/auth'
    | '/_autenticated/advisor'
    | '/_autenticated/career-tips'
    | '/_autenticated/cv-and-letters'
    | '/_autenticated/goal-setter'
    | '/_autenticated/home'
    | '/api/ai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutenticatedRouteRoute: typeof AutenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAiRoute: typeof ApiAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_autenticated': {
      id: '/_autenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AutenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_autenticated/advisor': {
      id: '/_autenticated/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AutenticatedAdvisorRouteImport
      parentRoute: typeof AutenticatedRouteRoute
    }
    '/_autenticated/career-tips': {
      id: '/_autenticated/career-tips'
      path: '/career-tips'
      fullPath: '/career-tips'
      preLoaderRoute: typeof AutenticatedCareerTipsRouteImport
      parentRoute: typeof AutenticatedRouteRoute
    }
    '/_autenticated/cv-and-letters': {
      id: '/_autenticated/cv-and-letters'
      path: '/cv-and-letters'
      fullPath: '/cv-and-letters'
      preLoaderRoute: typeof AutenticatedCvAndLettersRouteImport
      parentRoute: typeof AutenticatedRouteRoute
    }
    '/_autenticated/goal-setter': {
      id: '/_autenticated/goal-setter'
      path: '/goal-setter'
      fullPath: '/goal-setter'
      preLoaderRoute: typeof AutenticatedGoalSetterRouteImport
      parentRoute: typeof AutenticatedRouteRoute
    }
    '/_autenticated/home': {
      id: '/_autenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AutenticatedHomeRouteImport
      parentRoute: typeof AutenticatedRouteRoute
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AutenticatedRouteRouteChildren {
  AutenticatedAdvisorRoute: typeof AutenticatedAdvisorRoute
  AutenticatedCareerTipsRoute: typeof AutenticatedCareerTipsRoute
  AutenticatedCvAndLettersRoute: typeof AutenticatedCvAndLettersRoute
  AutenticatedGoalSetterRoute: typeof AutenticatedGoalSetterRoute
  AutenticatedHomeRoute: typeof AutenticatedHomeRoute
}

const AutenticatedRouteRouteChildren: AutenticatedRouteRouteChildren = {
  AutenticatedAdvisorRoute: AutenticatedAdvisorRoute,
  AutenticatedCareerTipsRoute: AutenticatedCareerTipsRoute,
  AutenticatedCvAndLettersRoute: AutenticatedCvAndLettersRoute,
  AutenticatedGoalSetterRoute: AutenticatedGoalSetterRoute,
  AutenticatedHomeRoute: AutenticatedHomeRoute,
}

const AutenticatedRouteRouteWithChildren =
  AutenticatedRouteRoute._addFileChildren(AutenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutenticatedRouteRoute: AutenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAiRoute: ApiAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
