/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdvisorRouteImport } from './routes/_authenticated/advisor'
import { Route as AuthenticatedCareerTipsRouteImport } from './routes/_authenticated/career-tips'
import { Route as AuthenticatedCvAndLettersRouteImport } from './routes/_authenticated/cv-and-letters'
import { Route as AuthenticatedGoalSetterRouteImport } from './routes/_authenticated/goal-setter'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as ApiAiRouteImport } from './routes/api/ai'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdvisorRoute = AuthenticatedAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCareerTipsRoute = AuthenticatedCareerTipsRouteImport.update({
  id: '/career-tips',
  path: '/career-tips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCvAndLettersRoute =
  AuthenticatedCvAndLettersRouteImport.update({
    id: '/cv-and-letters',
    path: '/cv-and-letters',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGoalSetterRoute = AuthenticatedGoalSetterRouteImport.update({
  id: '/goal-setter',
  path: '/goal-setter',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/advisor': typeof AuthenticatedAdvisorRoute
  '/career-tips': typeof AuthenticatedCareerTipsRoute
  '/cv-and-letters': typeof AuthenticatedCvAndLettersRoute
  '/goal-setter': typeof AuthenticatedGoalSetterRoute
  '/home': typeof AuthenticatedHomeRoute
  '/api/ai': typeof ApiAiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/advisor': typeof AuthenticatedAdvisorRoute
  '/career-tips': typeof AuthenticatedCareerTipsRoute
  '/cv-and-letters': typeof AuthenticatedCvAndLettersRoute
  '/goal-setter': typeof AuthenticatedGoalSetterRoute
  '/home': typeof AuthenticatedHomeRoute
  '/api/ai': typeof ApiAiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/advisor': typeof AuthenticatedAdvisorRoute
  '/_authenticated/career-tips': typeof AuthenticatedCareerTipsRoute
  '/_authenticated/cv-and-letters': typeof AuthenticatedCvAndLettersRoute
  '/_authenticated/goal-setter': typeof AuthenticatedGoalSetterRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/api/ai': typeof ApiAiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/advisor'
    | '/career-tips'
    | '/cv-and-letters'
    | '/goal-setter'
    | '/home'
    | '/api/ai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/advisor'
    | '/career-tips'
    | '/cv-and-letters'
    | '/goal-setter'
    | '/home'
    | '/api/ai'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/advisor'
    | '/_authenticated/career-tips'
    | '/_authenticated/cv-and-letters'
    | '/_authenticated/goal-setter'
    | '/_authenticated/home'
    | '/api/ai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAiRoute: typeof ApiAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/advisor': {
      id: '/_authenticated/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AuthenticatedAdvisorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/career-tips': {
      id: '/_authenticated/career-tips'
      path: '/career-tips'
      fullPath: '/career-tips'
      preLoaderRoute: typeof AuthenticatedCareerTipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cv-and-letters': {
      id: '/_authenticated/cv-and-letters'
      path: '/cv-and-letters'
      fullPath: '/cv-and-letters'
      preLoaderRoute: typeof AuthenticatedCvAndLettersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goal-setter': {
      id: '/_authenticated/goal-setter'
      path: '/goal-setter'
      fullPath: '/goal-setter'
      preLoaderRoute: typeof AuthenticatedGoalSetterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdvisorRoute: typeof AuthenticatedAdvisorRoute
  AuthenticatedCareerTipsRoute: typeof AuthenticatedCareerTipsRoute
  AuthenticatedCvAndLettersRoute: typeof AuthenticatedCvAndLettersRoute
  AuthenticatedGoalSetterRoute: typeof AuthenticatedGoalSetterRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdvisorRoute: AuthenticatedAdvisorRoute,
  AuthenticatedCareerTipsRoute: AuthenticatedCareerTipsRoute,
  AuthenticatedCvAndLettersRoute: AuthenticatedCvAndLettersRoute,
  AuthenticatedGoalSetterRoute: AuthenticatedGoalSetterRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAiRoute: ApiAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
